/**
 * Intended public vs signed-in surfaces. Enforcement is resource-based:
 * pages call `requireProductAccess` / `auth()`, APIs call
 * `requireWorkspaceUser` / `requirePrismaUser`. `proxy.ts` only runs Clerk
 * session plumbing.
 */
export const authConfig = {
  publicRoutes: [
    "/",
    "/sign-in",
    "/sign-up",
    "/login",
    "/signup",
    "/guest",
    "/privacy",
    "/terms",
    "/offline",
    "/s",
    "/s/:path*",
    "/build-with-aila",
    "/project-discovery",
    "/products/intelligence",
    "/api/project-inquiry",
    "/api/paystack/webhook",
    "/api/webhooks/clerk",
    "/api/cron",
  ],

  protectedRoutes: [
    "/dashboard",
    "/billing",
    "/products/ailalegal",
    "/products/business",
    "/products/automation",
    "/products/commerce",
    "/products/ads",
    "/products/daily",
    "/products/calendar",
    "/products/sites",
    "/products/apps",
    "/products/flow",
    "/products/writer",
    "/products/translate",
    "/products/documents",
    "/products/coding",
    "/products/career",
    "/products/education",
    "/products/health",
    "/products/finance",
    "/products/travel",
    "/products/shipping",
    "/api/ai",
    "/api/calendar",
    "/api/business",
    "/api/automation",
    "/api/commerce",
    "/api/ads",
    "/api/daily",
    "/api/apps",
    "/api/sites",
    "/api/flow",
    "/api/writer",
    "/api/translate",
    "/api/documents",
    "/api/coding",
    "/api/career",
    "/api/education",
    "/api/health",
    "/api/finance",
    "/api/travel",
    "/api/shipping",
    "/api/legal",
    "/api/dashboard",
    "/api/billing",
  ],
};
