import { ProductDefinition } from "./types";

export const PRODUCTS: ProductDefinition[] = [
    {
        id: "intelligence",
        name: "Aila Intelligence",
        description: "Enterprise AI workspace",
        route: "/products/intelligence",
        category: "AI",
        aiPrompt: "intelligence",
        enabled: true,
        icon: "Sparkles",
    },
    {
        id: "legal",
        name: "Aila Legal",
        description: "Legal AI workspace",
        route: "/products/ailalegal",
        category: "Legal",
        aiPrompt: "legal",
        enabled: true,
        icon: "Scale",
    },
    {
        id: "health",
        name: "Aila Health",
        description: "Healthcare intelligence",
        route: "/products/health",
        category: "Healthcare",
        aiPrompt: "health",
        enabled: true,
        icon: "HeartPulse",
    },
    {
        id: "business",
        name: "Aila Business",
        description: "Business intelligence",
        route: "/products/business",
        category: "Business",
        aiPrompt: "business",
        enabled: true,
        icon: "Briefcase",
    },
    {
        id: "automation",
        name: "Aila Automation",
        description: "Automation & AI agents",
        route: "/products/automation",
        category: "AI",
        aiPrompt: "automation",
        enabled: true,
        icon: "Bot",
    },
    {
        id: "apps",
        name: "Aila Apps",
        description: "Mobile applications",
        route: "/products/apps",
        category: "Development",
        aiPrompt: "apps",
        enabled: true,
        icon: "Smartphone",
    },
    {
        id: "sites",
        name: "Aila Sites",
        description: "Website platform",
        route: "/products/sites",
        category: "Development",
        aiPrompt: "sites",
        enabled: true,
        icon: "Globe",
    },
    {
        id: "flow",
        name: "Aila Flow",
        description: "Workflow automation",
        route: "/products/flow",
        category: "Productivity",
        aiPrompt: "flow",
        enabled: true,
        icon: "Workflow",
    },

    // Planned Products

    {
        id: "finance",
        name: "Aila Finance",
        description: "Financial intelligence",
        route: "/products/finance",
        category: "Business",
        aiPrompt: "finance",
        enabled: false,
        icon: "Wallet",
    },
    {
        id: "commerce",
        name: "Aila Commerce",
        description: "Commerce platform",
        route: "/products/commerce",
        category: "Commerce",
        aiPrompt: "commerce",
        enabled: false,
        icon: "ShoppingCart",
    },
    {
        id: "crm",
        name: "Aila CRM",
        description: "Customer relationship management",
        route: "/products/crm",
        category: "Business",
        aiPrompt: "crm",
        enabled: false,
        icon: "Users",
    },
    {
        id: "analytics",
        name: "Aila Analytics",
        description: "Business analytics",
        route: "/products/analytics",
        category: "Business",
        aiPrompt: "analytics",
        enabled: false,
        icon: "BarChart3",
    },
];