import {
    Brain,
    Scale,
    BriefcaseBusiness,
    Bot,
    Globe,
    AppWindow,
    GitBranch,
    Code2,
    HeartPulse,
    Truck,
    ShoppingCart,
    Landmark,
    Users,
    BarChart3,
    Megaphone,
    Share2,
    Cloud,
    Folder,
    Calendar,
    Mail,
    Video,
    KeyRound,
    Wrench,
    Settings,
} from "lucide-react";

export const products = [
    // Existing Products
    {
        id: "intelligence",
        name: "Aila Intelligence",
        href: "/products/intelligence",
        icon: Brain,
        status: "live",
        description: "Enterprise AI intelligence workspace.",
    },
    {
        id: "legal",
        name: "Aila Legal",
        href: "/products/ailalegal",
        icon: Scale,
        status: "live",
        description: "Legal AI and document intelligence.",
    },
    {
        id: "business",
        name: "Aila Business",
        href: "/products/business",
        icon: BriefcaseBusiness,
        status: "live",
        description: "Business intelligence and operations.",
    },
    {
        id: "automation",
        name: "Aila Automation",
        href: "/products/automation",
        icon: Bot,
        status: "live",
        description: "Workflow automation platform.",
    },
    {
        id: "sites",
        name: "Aila Sites",
        href: "/products/sites",
        icon: Globe,
        status: "live",
        description: "Website platform.",
    },
    {
        id: "apps",
        name: "Aila Apps",
        href: "/products/apps",
        icon: AppWindow,
        status: "live",
        description: "Application development.",
    },
    {
        id: "flow",
        name: "Aila Flow",
        href: "/products/flow",
        icon: GitBranch,
        status: "live",
        description: "Business process management.",
    },

    // Future Products
    {
        id: "coding",
        name: "Aila Coding",
        href: "/products/coding",
        icon: Code2,
        status: "coming-soon",
        description: "AI software engineering.",
    },
    {
        id: "health",
        name: "Aila Health",
        href: "/products/health",
        icon: HeartPulse,
        status: "coming-soon",
        description: "Healthcare intelligence.",
    },
    {
        id: "shipping",
        name: "Aila Shipping",
        href: "/products/shipping",
        icon: Truck,
        status: "coming-soon",
        description: "Logistics platform.",
    },
    {
        id: "commerce",
        name: "Aila Commerce",
        href: "/products/commerce",
        icon: ShoppingCart,
        status: "coming-soon",
        description: "Commerce ecosystem.",
    },
    {
        id: "finance",
        name: "Aila Finance",
        href: "/products/finance",
        icon: Landmark,
        status: "coming-soon",
        description: "Financial platform.",
    },
    {
        id: "crm",
        name: "Aila CRM",
        href: "/products/crm",
        icon: Users,
        status: "coming-soon",
        description: "Customer relationship management.",
    },
    {
        id: "analytics",
        name: "Aila Analytics",
        href: "/products/analytics",
        icon: BarChart3,
        status: "coming-soon",
        description: "Business analytics.",
    },
    {
        id: "ads",
        name: "Aila Ads",
        href: "/products/ads",
        icon: Megaphone,
        status: "coming-soon",
        description: "Advertising platform.",
    },
    {
        id: "social",
        name: "Aila Social",
        href: "/products/social",
        icon: Share2,
        status: "coming-soon",
        description: "Social platform.",
    },
    {
        id: "cloud",
        name: "Aila Cloud",
        href: "/products/cloud",
        icon: Cloud,
        status: "coming-soon",
        description: "Cloud infrastructure.",
    },
    {
        id: "files",
        name: "Aila Files",
        href: "/products/files",
        icon: Folder,
        status: "coming-soon",
        description: "File management.",
    },
    {
        id: "calendar",
        name: "Aila Calendar",
        href: "/products/calendar",
        icon: Calendar,
        status: "coming-soon",
        description: "Scheduling platform.",
    },
    {
        id: "email",
        name: "Aila Mail",
        href: "/products/email",
        icon: Mail,
        status: "coming-soon",
        description: "Enterprise email.",
    },
    {
        id: "meetings",
        name: "Aila Meetings",
        href: "/products/meetings",
        icon: Video,
        status: "coming-soon",
        description: "Meetings platform.",
    },
    {
        id: "api",
        name: "Aila API",
        href: "/products/api",
        icon: KeyRound,
        status: "coming-soon",
        description: "Developer APIs.",
    },
    {
        id: "developer",
        name: "Aila Developer",
        href: "/products/developer",
        icon: Wrench,
        status: "coming-soon",
        description: "Developer tools.",
    },
    {
        id: "settings",
        name: "Settings",
        href: "/settings",
        icon: Settings,
        status: "system",
        description: "Platform settings.",
    },
];